#!/usr/bin/env node
import fs from 'fs';
import path from 'path';
import readline from 'readline';
import BlockchainNode from '../index';
import { KeyManager } from '../blockchain/crypto/KeyManager';

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = (query: string): Promise<string> => {
    return new Promise((resolve) => rl.question(query, resolve));
};

async function setupEnv() {
    const envPath = path.resolve(process.cwd(), '.env');
    if (fs.existsSync(envPath)) {
        console.log('✅ Configuration file (.env) found.');
        return;
    }

    console.log('\n=============================================');
    console.log('   TraceNet V2.5 Node Configuration Wizard   ');
    console.log('=============================================\n');
    console.log('No .env file found. Let\'s set up your node.\n');

    const port = await question('1. Enter Port (default: 3000): ') || '3000';

    let validatorId = await question('2. Enter Validator ID (leave empty to generate): ');
    if (!validatorId) {
        // Generate a random one
        const keys = KeyManager.generateKeyPair();
        validatorId = `VAL_${keys.publicKey.substring(0, 8)}`;
        console.log(`   -> Generated Validator ID: ${validatorId}`);
    }

    const peers = await question('3. Enter Bootnode Peers (comma separated URL, optional): ');

    const publicHost = await question('4. Enter Public IP/Hostname (e.g. 203.0.113.1 or mynode.com, optional): ');

    const envContent = `
PORT=${port}
# System Configuration
GENESIS_VALIDATOR_ID=SYSTEM_GENESIS_VALIDATOR
BLOCK_TIME_MS=5000
MAX_TRANSACTIONS_PER_BLOCK=1000

# Network Configuration
PEERS=${peers}
PUBLIC_HOST=${publicHost}

# Validator Configuration
VALIDATOR_ID=${validatorId}

# Autogenerated by TraceNet CLI
`;

    fs.writeFileSync(envPath, envContent.trim());
    console.log('\n✅ Configuration saved to .env\n');
}

async function main() {
    try {
        await setupEnv();

        console.log('🚀 Starting TraceNet Node...');
        rl.close();

        // Start the node
        const node = new BlockchainNode();
        node.start();

        // Handle signals
        process.on('SIGINT', () => {
            console.log('\nStopping node...');
            node.stop();
            process.exit(0);
        });

    } catch (error) {
        console.error('Failed to start node:', error);
        process.exit(1);
    }
}

main();
